# Generated by Django 5.1.7 on 2025-05-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250506_1946'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "orders_orderitem_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "product_id" integer NOT NULL,
                "product_name" varchar(255) NOT NULL,
                "quantity" integer unsigned NOT NULL CHECK ("quantity" >= 0),
                "price" decimal NOT NULL,
                "order_id" bigint NOT NULL REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            INSERT OR IGNORE INTO "orders_orderitem_new" (id, product_id, product_name, quantity, price, order_id)
            SELECT id, product_id, 'Unknown Item', quantity, price, order_id FROM "orders_orderitem";
            DROP TABLE IF EXISTS "orders_orderitem";
            ALTER TABLE "orders_orderitem_new" RENAME TO "orders_orderitem";
            CREATE INDEX IF NOT EXISTS "orders_orderitem_order_id_fe61a34d" ON "orders_orderitem" ("order_id");
            """,
            """
            DROP TABLE IF EXISTS "orders_orderitem";
            """
        )
    ]
