# Generated by Django 5.1.7 on 2025-05-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20250506_1951'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='orders_orderitem',
        ),
    ]
